global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter_master'
    static_configs:
      - targets: ['node_exporter_master:9100']

  - job_name: 'node_exporter_slave'
    static_configs:
      - targets: ['node_exporter_slave:9100']

  - job_name: 'mysql_master'
    static_configs:
      - targets: ['mysqld_exporter_master:9104']

  - job_name: 'mysql_slave'
    static_configs:
      - targets: ['mysqld_exporter_slave:9105']

  - job_name: 'proxysql'
    static_configs:
      - targets: ['proxysql:6070']